---
# tasks file for install-packages
- name: install packages using yum
  yum:
   name: "{{ item }}"
   state: installed
   validate_certs: False
  with_items: "{{ rpm }}"
  become: true

- name: send email once the packages are installed
  mail:
   host: smtp.gmail.com
   port: 587
   username: syedhussain.linux
   password: Spyker@12
#   from: syedhussain.linux@gmail.com
   to: syedhussain.linux@gmail.com
   subject: packages are now installed
   subtype: html
   body: '
     <br>Hi Syed,<br><br>
     <br>packages are now installed.<br>
     <br> thanks '
